
{{- if .Values.products.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: products-http    # service name , just like  products deployment!
  labels:
    app: products   # reference to this service , just like  products deployment!
spec:
  type: ClusterIP                   
  selector:
      app: products
  ports:
    - protocol: TCP
      port: {{ .Values.products.port.http }}       # service listens
      targetPort: {{ .Values.products.port.http }} # provide http NETWORK : pod listens
{{- end }}